# Generated by Django 6.0.1 on 2026-01-27 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datospersonales',
            fields=[
                ('idperfil', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcionperfil', models.CharField(blank=True, max_length=50, null=True)),
                ('perfilactivo', models.IntegerField(blank=True, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=60, null=True)),
                ('nombres', models.CharField(blank=True, max_length=60, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=20, null=True)),
                ('lugarnacimiento', models.CharField(blank=True, max_length=60, null=True)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('numerocedula', models.CharField(blank=True, max_length=10, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('estadocivil', models.CharField(blank=True, max_length=50, null=True)),
                ('licenciaconducir', models.CharField(blank=True, max_length=6, null=True)),
                ('telefonoconvencional', models.CharField(blank=True, max_length=15, null=True)),
                ('telefonofijo', models.CharField(blank=True, max_length=15, null=True)),
                ('direcciontrabajo', models.CharField(blank=True, max_length=50, null=True)),
                ('direcciondomiciliaria', models.CharField(blank=True, max_length=50, null=True)),
                ('sitioweb', models.CharField(blank=True, max_length=60, null=True)),
                ('foto_perfil_url', models.URLField(blank=True, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(blank=True, default=True, null=True)),
                ('mostrar_experiencia', models.BooleanField(default=True)),
                ('mostrar_cursos', models.BooleanField(default=True)),
                ('mostrar_reconocimientos', models.BooleanField(default=True)),
                ('mostrar_productos_academicos', models.BooleanField(default=True)),
                ('mostrar_productos_laborales', models.BooleanField(default=True)),
                ('mostrar_ventagarage', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'datospersonales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cursosrealizados',
            fields=[
                ('idcursorealizado', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombrecurso', models.CharField(blank=True, max_length=100, null=True)),
                ('fechainicio', models.DateField(blank=True, null=True)),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('totalhoras', models.IntegerField(blank=True, null=True)),
                ('descripcioncurso', models.CharField(blank=True, max_length=100, null=True)),
                ('entidadpatrocinadora', models.CharField(blank=True, max_length=100, null=True)),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=60, null=True)),
                ('emailempresapatrocinadora', models.CharField(blank=True, max_length=60, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(blank=True, default=True, null=True)),
                ('rutacertificado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Link Externo')),
                ('archivo_digital', models.FileField(blank=True, null=True, upload_to='certificados/cursos/', verbose_name='Subir PDF/Imagen')),
                ('idperfilconqueestaactivo', models.ForeignKey(blank=True, db_column='idperfilconqueestaactivo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cv.datospersonales')),
            ],
            options={
                'db_table': 'cursosrealizados',
                'ordering': ['-fechainicio'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Experiencialaboral',
            fields=[
                ('idexperiencilaboral', models.BigAutoField(primary_key=True, serialize=False)),
                ('cargodesempenado', models.CharField(blank=True, max_length=100, null=True)),
                ('nombrempresa', models.CharField(blank=True, max_length=50, null=True)),
                ('lugarempresa', models.CharField(blank=True, max_length=50, null=True)),
                ('emailempresa', models.CharField(blank=True, max_length=100, null=True)),
                ('sitiowebempresa', models.CharField(blank=True, max_length=100, null=True)),
                ('nombrecontactoempresarial', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoempresarial', models.CharField(blank=True, max_length=60, null=True)),
                ('fechainiciogestion', models.DateField(blank=True, null=True)),
                ('fechafingestion', models.DateField(blank=True, null=True)),
                ('descripcionfunciones', models.CharField(blank=True, max_length=100, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(blank=True, default=True, null=True)),
                ('rutacertificado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Link Externo')),
                ('archivo_digital', models.FileField(blank=True, null=True, upload_to='certificados/experiencia/', verbose_name='Subir PDF/Imagen')),
                ('idperfilconqueestaactivo', models.ForeignKey(blank=True, db_column='idperfilconqueestaactivo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='cv.datospersonales')),
            ],
            options={
                'db_table': 'experiencialaboral',
                'ordering': ['-fechainiciogestion'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productosacademicos',
            fields=[
                ('idproductoacademico', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombrerecurso', models.CharField(blank=True, max_length=100, null=True)),
                ('clasificador', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(blank=True, default=True, null=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(blank=True, db_column='idperfilconqueestaactivo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to='cv.datospersonales')),
            ],
            options={
                'db_table': 'productosacademicos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productoslaborales',
            fields=[
                ('idproductoslaborales', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaproducto', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(blank=True, default=True, null=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(blank=True, db_column='idperfilconqueestaactivo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_laborales', to='cv.datospersonales')),
            ],
            options={
                'db_table': 'productoslaborales',
                'ordering': ['-fechaproducto'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reconocimientos',
            fields=[
                ('idreconocimiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('tiporeconocimiento', models.CharField(blank=True, max_length=20, null=True)),
                ('fechareconocimiento', models.DateField(blank=True, null=True)),
                ('descripcionreconocimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('entidadpatrocinadora', models.CharField(blank=True, max_length=100, null=True)),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=60, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(blank=True, default=True, null=True)),
                ('rutacertificado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Link Externo')),
                ('archivo_digital', models.FileField(blank=True, null=True, upload_to='certificados/logros/', verbose_name='Subir PDF/Imagen')),
                ('idperfilconqueestaactivo', models.ForeignKey(blank=True, db_column='idperfilconqueestaactivo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='cv.datospersonales')),
            ],
            options={
                'db_table': 'reconocimientos',
                'ordering': ['-fechareconocimiento'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ventagarage',
            fields=[
                ('idventagaraje', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=10)),
                ('fechapublicacion', models.DateField()),
                ('imagen', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('archivo_digital', models.FileField(blank=True, null=True, upload_to='garage/', verbose_name='Foto Real del Producto')),
                ('idperfilconqueestaactivo', models.ForeignKey(blank=True, db_column='idperfilconqueestaactivo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_garage', to='cv.datospersonales')),
            ],
            options={
                'db_table': 'ventagarage',
                'ordering': ['-fechapublicacion'],
                'managed': True,
            },
        ),
    ]
