# Generated by Django 6.0.1 on 2026-01-28 05:57

import cv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='archivo_digital',
            field=models.FileField(blank=True, null=True, upload_to=cv.models.upload_cursos, verbose_name='Subir PDF/Imagen'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='archivo_digital',
            field=models.FileField(blank=True, null=True, upload_to=cv.models.upload_experiencia, verbose_name='Subir PDF/Imagen'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='archivo_digital',
            field=models.FileField(blank=True, null=True, upload_to=cv.models.upload_logros, verbose_name='Subir PDF/Imagen'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='archivo_digital',
            field=models.FileField(blank=True, null=True, upload_to=cv.models.upload_garage, verbose_name='Foto Real del Producto'),
        ),
    ]
