# Generated by Django 6.0.1 on 2026-01-28 07:03

import cv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_alter_cursosrealizados_archivo_digital_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productosacademicos',
            options={},
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fechanacimiento',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_edad_18_100], verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='foto_perfil_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link Foto Perfil'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='numerocedula',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[cv.models.validar_10_digitos], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonoconvencional',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[cv.models.validar_10_digitos], verbose_name='Celular'),
        ),
    ]
