# Generated by Django 6.0.1 on 2026-01-28 14:19

import cv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_productosacademicos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='totalhoras',
            field=models.IntegerField(blank=True, null=True, validators=[cv.models.validar_positivo], verbose_name='Total Horas'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fechanacimiento',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_edad_18_100], verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='foto_perfil_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link Foto Perfil (Cloudinary)'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[cv.models.validar_positivo], verbose_name='Precio'),
        ),
    ]
