# Generated by Django 6.0.1 on 2026-01-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_alter_cursosrealizados_totalhoras_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productosacademicos',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email de Contacto'),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='emailempresapatrocinadora',
            field=models.EmailField(blank=True, max_length=60, null=True, verbose_name='Email Patrocinador'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='foto_perfil_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link Foto Perfil'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='emailempresa',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Empresa'),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='clasificador',
            field=models.CharField(blank=True, choices=[('Articulo cientifico', 'Artículo científico'), ('Ponencia', 'Ponencia'), ('Proyecto de investigacion', 'Proyecto de investigación'), ('Libro', 'Libro'), ('Capitulo de libro', 'Capítulo de libro'), ('Recurso didactico', 'Recurso didáctico')], max_length=50, null=True, verbose_name='Tipo de Producto'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='tiporeconocimiento',
            field=models.CharField(blank=True, choices=[('Publico', 'Público'), ('Privado', 'Privado'), ('Academico', 'Académico')], max_length=20, null=True, verbose_name='Tipo de Reconocimiento'),
        ),
    ]
