# Generated by Django 6.0.1 on 2026-01-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_alter_productosacademicos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='estadocivil',
            field=models.CharField(blank=True, choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Viudo', 'Viudo'), ('Divorciado', 'Divorciado'), ('Union de hecho', 'Unión de hecho')], max_length=50, null=True, verbose_name='Estado Civil'),
        ),
    ]
