# Generated by Django 6.0.1 on 2026-01-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_alter_datospersonales_estadocivil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='licenciaconducir',
            field=models.CharField(blank=True, choices=[('A', 'Tipo A: Motocicletas, ciclomotores, tricar y cuadrones'), ('B', 'Tipo B: Automóviles y camionetas (hasta 1.75 ton)'), ('F', 'Tipo F: Automotores especiales adaptados (Discapacidad)'), ('A1', 'Tipo A1: Mototaxis o tricimotos de servicio comercial'), ('C', 'Tipo C: Taxis, camionetas livianas (hasta 3.5 ton)'), ('C1', 'Tipo C1: Vehículos policiales, ambulancias, militares'), ('D', 'Tipo D: Servicio de pasajeros (intracantonal, interprovincial)'), ('D1', 'Tipo D1: Escolar, institucional y turismo'), ('E', 'Tipo E: Camiones pesados y extra pesados (tráiler, volqueta)'), ('E1', 'Tipo E1: Ferrocarriles, autoferros, trolebuses'), ('G', 'Tipo G: Maquinaria agrícola y equipo caminero')], max_length=50, null=True, verbose_name='Tipo de Licencia'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Prefiero no decir', 'Prefiero no decir')], max_length=20, null=True, verbose_name='Género / Sexo'),
        ),
    ]
